version: '3.9'
services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - qdrant
    command: python src/run_etl.py

  qdrant:
    image: qdrant/qdrant
    ports:
      - '6333:6333'
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
